feat: update dockerfile example

diff --git a/functions/clamav-scan/Dockerfile b/functions/clamav-scan/Dockerfile
--- a/functions/clamav-scan/Dockerfile
+++ b/functions/clamav-scan/Dockerfile
@@ -21,49 +21,64 @@ RUN npm install && \
 # ========================================
 FROM --platform=linux/x86_64 public.ecr.aws/lambda/nodejs:20 as runtime
 
-#
-# 1) Download latest ClamAV from https://www.clamav.net/downloads
-# 2) Install using `rpm` and it requires full path for local packages
-# 3) Remove the downloaded package and clean up for smaller runtime image
-#
 ENV CLAMAV_PKG=clamav-1.2.1.linux.x86_64.rpm
-RUN set -ex && \
-    dnf install wget -y && \
-    wget https://www.clamav.net/downloads/production/${CLAMAV_PKG} && \
-    rpm -ivh "${LAMBDA_TASK_ROOT}/${CLAMAV_PKG}" && \
-    rm -rf ${CLAMAV_PKG} && \
-    dnf remove wget -y && \
+RUN <<-EOF
+    set -ex
+
+    #
+    # install glibc-langpack-en to support english language and utf-8
+    # this was required by clamscan to avoid error "WARNING: Failed to set locale"
+    #
+    dnf install wget glibc-langpack-en -y
+
+    # 
+    # 1) download latest ClamAV from https://www.clamav.net/downloads
+    # 2) install using `rpm` and it requires full path for local packages
+    # 3) remove the downloaded package and clean up for smaller runtime image
+    # 
+    wget https://www.clamav.net/downloads/production/${CLAMAV_PKG}
+    rpm -ivh "${LAMBDA_TASK_ROOT}/${CLAMAV_PKG}"
+    rm -rf ${CLAMAV_PKG}
+    dnf remove wget -y
     dnf clean all
 
-#
-# install glibc-langpack-en to support english language and utf-8
-# this was required by clamscan to avoid error "WARNING: Failed to set locale"
-#
-RUN dnf install glibc-langpack-en -y
+    #
+    # the current working directory is "/var/task" as defined in the base image:
+    # https://github.com/aws/aws-lambda-base-images/blob/nodejs20.x/Dockerfile.nodejs20.x
+    #
+    # 1) "lib/database" is the path to download the virus database
+    # 2) "freshclam.download.log" and "freshclam.conf.log" are the log files for freshclam CLI
+    #
+    mkdir -p ${LAMBDA_TASK_ROOT}/lib/database
+    touch ${LAMBDA_TASK_ROOT}/lib/{freshclam.download.log,freshclam.conf.log}
+    chmod -R 777 ${LAMBDA_TASK_ROOT}/lib
 
-#
-# the current working directory is "/var/task" as defined in the base image:
-# https://github.com/aws/aws-lambda-base-images/blob/nodejs20.x/Dockerfile.nodejs20.x
-#
-# 1) "lib/database" is the path to download the virus database
-# 2) "freshclam.download.log" and "freshclam.conf.log" are the log files for freshclam CLI
-#
-RUN mkdir -p /var/task/lib/database
-RUN touch /var/task/lib/{freshclam.download.log,freshclam.conf.log}
-RUN chmod -R 777 /var/task/lib
+    #
+    # default configuration path for freshclam is "/usr/local/etc/freshclam.conf"
+    # we create a symbolic link to the default configuration path and copy our custom config file
+    #
+    ln -s /usr/local/etc/freshclam.conf ${LAMBDA_TASK_ROOT}/lib/freshclam.conf
+EOF
 
-#
-# default configuration path for freshclam is "/usr/local/etc/freshclam.conf"
-# we create a symbolic link to the default configuration path and copy our custom configuration file
-#
-RUN ln -s /usr/local/etc/freshclam.conf /var/task/lib/freshclam.conf
 COPY freshclam.conf /var/task/lib/freshclam.conf
 
 #
 # freshclam CLI is a virus database update tool for ClamAV, documentation:
 # https://linux.die.net/man/1/freshclam
 #
-RUN freshclam --verbose --stdout --user root --log=/var/task/lib/freshclam.download.log --datadir=/var/task/lib/database
+RUN <<-EOF
+    set -ex
+    export LOG_FILE_PATH="${LAMBDA_TASK_ROOT}/lib/freshclam.conf.log"
+
+    freshclam --verbose --stdout --user root \
+        --log=${LOG_FILE_PATH} \
+        --datadir=${LAMBDA_TASK_ROOT}/lib/database
+
+    if grep -q "Can't download daily.cvd\|Can't download main.cvd\|Can't download bytecode.cvd" ${LOG_FILE_PATH}; then
+        echo "ERROR: Unable to download ClamAV database files - your request may be being rate limited"
+        exit 1;
+    fi
+EOF
 
 #
 # copy application files from the builder image
